CREATE TABLE "knowledge_base_chunks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "knowledge_base_chunks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"knowledge_base_id" uuid NOT NULL,
	"chunk" text NOT NULL,
	"embedding" vector(1536) NOT NULL,
	"created_at" timestamp with time zone DEFAULT timezone('utc'::text, now())
);
--> statement-breakpoint
ALTER TABLE "knowledge_base_chunks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "resumes" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"user_id" uuid NOT NULL,
	"slug" text NOT NULL,
	"content" jsonb NOT NULL,
	"theme" text DEFAULT 'modern' NOT NULL,
	"is_public" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
	"updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
	CONSTRAINT "resumes_slug_unique" UNIQUE("slug"),
	CONSTRAINT "unique_user_slug" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "resumes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY "Authenticated users can create shares" ON "chat_shares" CASCADE;--> statement-breakpoint
DROP POLICY "Enable read access for all users" ON "chat_shares" CASCADE;--> statement-breakpoint
DROP TABLE "chat_shares" CASCADE;--> statement-breakpoint
ALTER TABLE "knowledge_bases" ADD COLUMN "instruction" text;--> statement-breakpoint
ALTER TABLE "knowledge_base_chunks" ADD CONSTRAINT "knowledge_base_chunks_knowledge_base_id_knowledge_bases_id_fk" FOREIGN KEY ("knowledge_base_id") REFERENCES "public"."knowledge_bases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resumes" ADD CONSTRAINT "resumes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "knowledge_bases" DROP COLUMN "detail_embedding";--> statement-breakpoint
CREATE POLICY "Public read access for chunks" ON "knowledge_base_chunks" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Users can view their own resumes" ON "resumes" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));--> statement-breakpoint
CREATE POLICY "Anyone can view public resumes" ON "resumes" AS PERMISSIVE FOR SELECT TO public USING ((is_public = true));--> statement-breakpoint
CREATE POLICY "Users can insert their own resumes" ON "resumes" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));--> statement-breakpoint
CREATE POLICY "Users can update their own resumes" ON "resumes" AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));--> statement-breakpoint
CREATE POLICY "Users can delete their own resumes" ON "resumes" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));