
-- Create knowledge_base_chunks table
CREATE TABLE IF NOT EXISTS knowledge_base_chunks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_base_id uuid NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
  chunk text NOT NULL,
  embedding vector(1536) NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE knowledge_base_chunks ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access (simplified for now, can be tightened later)
CREATE POLICY "Public read access for chunks" ON knowledge_base_chunks
  FOR SELECT TO public USING (true);

-- Create HNSW index for vector search
CREATE INDEX IF NOT EXISTS knowledge_base_chunks_embedding_idx ON knowledge_base_chunks USING hnsw (embedding vector_cosine_ops);
