"use client";

import { motion } from "framer-motion";
import { useRouter } from "next/navigation";
import useSupabaseSession from "./hooks/useSupabaseSession";
import Link from "next/link";
import { signOut } from "./login/action";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

const containerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.2,
      duration: 0.8,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  show: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.5,
    },
  },
};

const MotionButton = motion(Button);

export default function Home() {
  const router = useRouter();

  const { session } = useSupabaseSession();

  return (
    <div className="w-full h-screen flex flex-col">
      <div className="absolute top-0 w-full px-6 py-4 flex justify-between items-center">
        <span className="text-white text-xl font-bold">✨ DocAider</span>
        <div className="flex gap-4 text-sm text-gray-300">
          {session ? (
            <>
              <Button variant="ghost" onClick={() => router.push("/chat")}>
                Dashboard
              </Button>
              <Button
                variant="ghost"
                onClick={() =>
                  signOut().then(() => {
                    window.location.reload();
                  })
                }
              >
                Sign Out
              </Button>
            </>
          ) : (
            <Button variant="ghost" onClick={() => router.push("/login")}>
              Sign In
            </Button>
          )}
        </div>
      </div>
      <video
        className="absolute inset-0 w-full h-full object-cover opacity-10 pointer-events-none blur-xs"
        autoPlay
        loop
        muted
        playsInline
        src="/docaider-demo.mp4" // Replace with your actual video path
      />
      <div className="flex-1 flex flex-col items-center justify-center px-4 mt-12 lg:mt-0 py-8">
        <motion.div
          initial="hidden"
          animate="show"
          variants={containerVariants}
          className="text-center space-y-8 max-w-4xl relative"
        >
          <motion.h1
            variants={itemVariants}
            className="text-4xl md:mt-10 mt-6 md:text-6xl tracking-tight font-extrabold bg-gradient-to-r from-orange-500 to-red-500 bg-clip-text text-transparent"
          >
            Transform Text and Documents into Insights
          </motion.h1>

          <motion.p variants={itemVariants} className="text-xl text-gray-300">
            DocAider is your AI-powered assistant for processing documents,
            visualizing data, and getting smart insights - all in one place.
          </motion.p>

          <motion.div
            variants={itemVariants}
            className="mt-4 text-gray-400 text-sm text-center"
          >
            Upload documents, ask questions, and get visual insights - powered
            by AI.
          </motion.div>

          <motion.div
            variants={itemVariants}
            className="flex flex-col md:flex-row gap-4 justify-center"
          >
            <MotionButton
              onClick={() => router.push("/chat")}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              size="lg"
              className="bg-gradient-to-r cursor-pointer from-orange-500 to-red-500 text-white px-8 py-4 rounded-full font-semibold text-lg transition-all hover:shadow-lg hover:shadow-orange-500/30"
            >
              Get Started
            </MotionButton>
          </motion.div>

          <section className="relative z-10 px-6 border-zinc-800">
            <motion.div
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
              className="max-w-6xl mx-auto flex flex-col items-center text-center space-y-8"
            >
              <h2 className="text-4xl md:text-2xl font-bold text-white">
                See It In Action
              </h2>
              <p className="text-gray-400 max-w-2xl">
                One prompt. One result. Watch how DocAider instantly turns text
                into rich, interactive visualizations.
              </p>

              <div className="relative rounded-xl overflow-hidden border border-zinc-800 shadow-lg w-full max-w-3xl mt-2">
                <motion.img
                  src="/example-screenshot2.png" // Replace with your real screenshot
                  alt="Example visualization generated by DocAider"
                  className="w-full"
                  initial={{ scale: 0.98, opacity: 0 }}
                  whileInView={{ scale: 1, opacity: 1 }}
                  transition={{ duration: 0.7 }}
                  viewport={{ once: true }}
                />
              </div>
            </motion.div>
          </section>
          <motion.div
            variants={itemVariants}
            className="mt-16 grid grid-cols-1 md:grid-cols-3 gap-8"
          >
            <Card className="bg-zinc-800/50 backdrop-blur-sm border-zinc-700 text-left">
              <CardHeader>
                <CardTitle className="text-2xl font-bold text-orange-500 mb-2">
                  Document Processing
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-400">
                  Upload PDFs and other documents to extract insights and
                  process content with AI.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-zinc-800/50 backdrop-blur-sm border-zinc-700 text-left">
              <CardHeader>
                <CardTitle className="text-2xl font-bold text-orange-500 mb-2">
                  AI-Powered Chat
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-400">
                  Get smart answers and insights through natural conversation
                  with our AI assistant.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-zinc-800/50 backdrop-blur-sm border-zinc-700 text-left">
              <CardHeader>
                <CardTitle className="text-2xl font-bold text-orange-500 mb-2">
                  Data Visualization
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-400">
                  Create beautiful, interactive charts from your data and
                  document content automatically.
                </p>
              </CardContent>
            </Card>
          </motion.div>
        </motion.div>
      </div>
      <footer className="w-full bg-zinc-900 border-t border-zinc-800 px-6 py-10 text-gray-400 text-sm">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="text-center md:text-left">
            <span className="font-bold text-white">✨ DocAider</span> &mdash;
            Turn text into stunning visualizations.
          </div>

          <div className="flex flex-wrap gap-4 justify-center md:justify-end text-gray-400">
            <Link href="/privacy" className="hover:text-white transition">
              Privacy
            </Link>
            <Link href="/terms" className="hover:text-white transition">
              Terms
            </Link>

            <Link href="/contact" className="hover:text-white transition">
              Contact
            </Link>
          </div>
        </div>

        <div className="mt-6 text-center text-xs text-gray-600">
          © {new Date().getFullYear()} DocAider. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
